# Generated by Django 5.2.8 on 2025-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobrole_skill_profile_current_workload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='can_assign_tasks',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='can_manage_projects',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='can_manage_tasks',
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
