# Generated by Django 5.2.8 on 2025-11-25 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_jobrole_can_assign_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_workload',
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s', to='core.jobrole'),
        ),
    ]
