# Generated by Django 5.2.8 on 2025-11-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_current_workload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_workload',
            field=models.IntegerField(default=0),
        ),
    ]
