# Generated by Django 5.2.8 on 2025-11-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_current_workload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.permission'),
        ),
    ]
