# Generated by Django 5.2.8 on 2025-11-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_permission_jobrole_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='code',
        ),
    ]
