# Generated by Django 5.2.8 on 2025-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='tasks_required', to='core.skill'),
        ),
    ]
