# Generated by Django 5.2.8 on 2025-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='tasks_required_for', to='core.skill'),
        ),
    ]
