# Generated by Django 5.2.8 on 2025-12-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_overall_rating_profile_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='impact',
            field=models.CharField(choices=[('normal', 'عادية'), ('medium', 'متوسطة'), ('heavy', 'ثقيلة')], default='normal', max_length=10),
        ),
    ]
