# Generated by Django 5.2.8 on 2025-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_impact'),
    ]

    operations = [
        
    ]
