# Generated by Django 5.2.8 on 2025-12-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('late', 'Late')], default='todo', max_length=20),
        ),
    ]
