# Generated by Django 5.2.8 on 2025-12-06 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('project_created', 'تم إنشاء مشروع جديد'), ('task_created', 'تم إنشاء مهمة جديدة'), ('task_updated', 'تم تحديث مهمة'), ('task_completed', 'تم اكتمال مهمة'), ('submission_added', 'تم رفع تسليم'), ('submission_approved', 'تمت الموافقة على تسليم'), ('submission_rejected', 'تم رفض تسليم')], max_length=50),
        ),
    ]
