# Generated by Django 5.2.8 on 2025-12-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_submission_reviewed_at_submission_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='manager_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
